pipeline:
  name: process_photo
description: process_photo the photos.
input:
  pfs:
    glob: /*
    repo: input_images
transform:
  cmd:
    - python3
    - /run.py
    - --input_folder=/pfs/input_images/
    - --output_folder=/pfs/out/
  image: nickharvey/abuela:latest